Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: Api
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /delete:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserDeleteFunction.Arn}/invocations
              responses: {}
          /register:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserRegisterFunction.Arn}/invocations
              responses: {}
          /ranking/{groupName}:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetRankingListFunction.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
  userGroup:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: userName
          AttributeType: S
        - AttributeName: groupName
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userName
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      GlobalSecondaryIndexes:
        - IndexName: GSI-groupName
          KeySchema:
            - AttributeName: groupName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  UserDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: UserDeleteFunction
      CodeUri: src/UserDeleteFunction
      Handler: main
      Runtime: go1.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          USERGROUP_TABLE_NAME: !Ref userGroup
          USERGROUP_TABLE_ARN: !GetAtt userGroup.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref userGroup
      Events:
        ApiPOSTdelete:
          Type: Api
          Properties:
            Path: /delete
            Method: POST
            RestApiId: !Ref Api
  UserDeleteFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${UserDeleteFunction}
  UserRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: UserRegisterFunction
      CodeUri: src/UserRegisterFunction
      Handler: main
      Runtime: go1.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          USERGROUP_TABLE_NAME: !Ref userGroup
          USERGROUP_TABLE_ARN: !GetAtt userGroup.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref userGroup
      Events:
        ApiPOSTregister:
          Type: Api
          Properties:
            Path: /register
            Method: POST
            RestApiId: !Ref Api
  UserRegisterFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${UserRegisterFunction}
  GetRankingListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetRankingListFunction
      CodeUri: src/GetRankingListFunction
      Handler: main
      Runtime: go1.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          USERGROUP_TABLE_NAME: !Ref userGroup
          USERGROUP_TABLE_ARN: !GetAtt userGroup.Arn
          ENV: prod
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref userGroup
      Events:
        ApiGETrankinggroupName:
          Type: Api
          Properties:
            Path: /ranking/{groupName}
            Method: GET
            RestApiId: !Ref Api
  GetRankingListFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetRankingListFunction}